# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands:
   - agent.name -equals mydockeragent
steps:
- script: |
    mkdir build
    g++ -o ./build/hello_world.exe ./test/pipeline/hello_world.cpp
  displayName: 'Testing compiler g++'

- script: |
    cd build
    hello_world.exe
    cd ..
  displayName: 'Run exe task'

- script: |
    rm -r build
  displayName: 'Cleanup'